spring.application.name=INTERNSHIP

spring.datasource.url=jdbc:postgresql://localhost:5432/AssignmentIMOTIVE
spring.datasource.username=postgres
spring.datasource.password=slidingwindow16

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true