version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: AssignmentIMOTIVE
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: slidingwindow16
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"